/*
 * DesktopApplication1AboutBox.java
 */

package ch.tkayser.budget.swing.common;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.WindowConstants;

import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ApplicationActionMap;
import org.jdesktop.application.ResourceMap;

import ch.tkayser.budget.swing.Constants;
import ch.tkayser.budget.swing.MainApplication;
import static ch.tkayser.budget.swing.widgets.UIFactory.*;

public class AboutDialog extends JDialog {

    private static final long serialVersionUID = 1L;

    //@formatter:off    
    private static final String AC_CLOSE = "closeDialog";
    
    // a resource and action map
    private ResourceMap                resourceMap;
    private ApplicationActionMap       actionMap;
    //@formatter:on

    public AboutDialog(JFrame parent) {
        super(parent);

        // get the resource and action map
        resourceMap = Application.getInstance().getContext().getResourceMap(getClass());
        actionMap = Application.getInstance(MainApplication.class).getContext().getActionMap(this.getClass(), this);

        // init the content
        initComponents();

    }

    @Action
    public void closeDialog() {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        // Close Button
        JButton btnClose = new JButton(actionMap.get(AC_CLOSE));
        getRootPane().setDefaultButton(btnClose);

        // Labels
        JLabel lblVersionLabel = createLabel(Constants.LBL_VERSION);
        JLabel lblVersionText = new JLabel();
        JLabel iconLabel = new JLabel();

        // label content and image
        String version = getClass().getPackage().getImplementationVersion();
        if (version == null) {
            version = resourceMap.getString(Constants.VERSION_PROPERTY);
        }
        
        lblVersionText.setText(version);
        iconLabel.setIcon(resourceMap.getIcon(Constants.ICON_BUDGET));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(layout
                .createSequentialGroup()
                .addComponent(iconLabel)
                .addGroup(
                        layout.createParallelGroup()
                                .addGroup(layout.createSequentialGroup().addComponent(lblVersionLabel).addComponent(lblVersionText))
                                .addComponent(btnClose, Alignment.TRAILING)));

        layout.setVerticalGroup(layout
                .createParallelGroup()
                .addComponent(iconLabel)
                .addGroup(
                        layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup().addComponent(lblVersionLabel).addComponent(lblVersionText))
                                .addComponent(btnClose)));

        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        
        // dialog properties
        setTitle(resourceMap.getString(Constants.DIALOG_TITEL));
        setModal(true);
        setName(getClass().getName());
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(MainApplication.getMainApplication().getMainFrame());
        
        resourceMap.injectComponents(this);

        pack();

    }
}
